app: Geeknr
mode: debug
gzip: true
mysql:
  dsn: >-
    tljs:tljs123456@tcp(192.168.28.25:3306)/zeus?charset=utf8&parseTime=True&loc=Local
  pool:
    min: 5
    max: 20
cors:
  enable: true
  allow_origins: "*"
  allow_headers: ["Content-Type","AccessToken","X-CSRF-Token", "Authorization","Token"]
  allow_methods: ["POST", "GET", "OPTIONS", "PUT", "DELETE"]
  allow_credentials: true
  max_age: 7200